#!/usr/bin/env bash
#
# The TLS mode, as a file Caddy imports.
#
# Shared by install.sh, gen-env.sh and tls.sh so the three cannot disagree about
# what a mode means. Source it; it defines functions and no state.
#
# Caddy's site block contains one line:
#
#     import /etc/caddy/tls/tls.caddy
#
# and this writes that file. A generated snippet rather than an environment
# variable in the Caddyfile, because a custom certificate needs *two* arguments
# — `tls <cert> <key>` — and how a `{$VAR}` expansion splits into tokens is a
# detail of Caddy's parser rather than something this project should depend on.
# A file whose content is exactly the directive has no such question in it.
#
# The import names a fixed file rather than a glob. A missing file stops Caddy
# with a clear error, which is the right failure for a TLS misconfiguration: the
# alternative — no `tls` directive at all — means Caddy chooses for itself, and
# for a public hostname that is an unexpected attempt at a real certificate.

# Where the mode file and any uploaded material live on the host. The Caddy
# container bind-mounts this directory read-only at /etc/caddy/tls.
tls_dir() {
  printf '%s/deploy/caddy/tls' "$1"
}

# The paths Caddy sees, which are not the paths on the host.
readonly TLS_CONTAINER_DIR="/etc/caddy/tls"
readonly TLS_CERT_NAME="velnox.crt"
readonly TLS_KEY_NAME="velnox.key"

# Classify a VELNOX_TLS value. One place, so every script agrees.
#
#   internal      Caddy's own CA. Right for an appliance reached by IP.
#   certificate   material supplied by the operator, in this directory.
#   <anything>    an email address: obtain a real certificate over ACME.
tls_mode_of() {
  case "$1" in
    internal | '') printf 'internal' ;;
    certificate) printf 'certificate' ;;
    *) printf 'acme' ;;
  esac
}

# Writes the directive Caddy imports. Idempotent; safe to call on every run.
#
# $1 repository root, $2 the VELNOX_TLS value.
write_tls_config() {
  local root="$1" value="$2"
  local dir
  dir="$(tls_dir "$root")"
  mkdir -p "$dir"
  chmod 700 "$dir"

  local directive
  case "$(tls_mode_of "$value")" in
    internal)
      directive='tls internal'
      ;;
    certificate)
      # Refuse rather than write a directive pointing at files that are not
      # there: Caddy would fail to start, and the reason would be a path in a
      # container log rather than a sentence here.
      if [[ ! -s "${dir}/${TLS_CERT_NAME}" || ! -s "${dir}/${TLS_KEY_NAME}" ]]; then
        echo "VELNOX_TLS=certificate but no certificate is installed in ${dir}." >&2
        echo "Run scripts/tls.sh --certificate=... --key=... first." >&2
        return 1
      fi
      directive="tls ${TLS_CONTAINER_DIR}/${TLS_CERT_NAME} ${TLS_CONTAINER_DIR}/${TLS_KEY_NAME}"
      ;;
    acme)
      # The address is the ACME account contact. Caddy validates it; a malformed
      # one fails at start rather than at first renewal.
      directive="tls ${value}"
      ;;
  esac

  cat >"${dir}/tls.caddy" <<EOF
# Generated by Velnox — do not edit.
#
# Written from VELNOX_TLS in .env by install.sh, gen-env.sh or scripts/tls.sh,
# and imported by deploy/caddy/Caddyfile. Editing this file by hand works until
# the next install or upgrade overwrites it; change VELNOX_TLS instead, or use
# scripts/tls.sh.
${directive}
EOF
  chmod 644 "${dir}/tls.caddy"
}
