import { randomBytes } from 'node:crypto';
import PDFDocument from 'pdfkit';
import { upgradeEncryptionToR6 } from './pdf-r6';

/**
 * The installation record: a PDF saying what was built, where, from what, and
 * how long it took.
 *
 * Two forms, chosen by the template:
 *
 * - **Without passwords** (`VELNOX_ONLY`): the record, and a line saying the
 *   passwords are in Velnox, where revealing them is audited.
 * - **With passwords, encrypted** (`ENCRYPTED_PDF`): AES-256, revision 6 (ISO
 *   32000-2), opened with a password that never travels in the same mail.
 *
 * Written in the recipient's language, with times in their time zone.
 */

export interface RecordInput {
  locale: 'en' | 'nl';
  timeZone: string;
  productVersion: string;
  hostname: string;
  vmid: number | null;
  clusterName: string;
  node: string;
  templateName: string;
  family: 'WINDOWS' | 'LINUX';
  addresses: string[];
  requestedBy: string | null;
  startedAt: Date | null;
  finishedAt: Date | null;
  /** Present only for an encrypted record. */
  accounts?: { name: string; password: string | null; administrator: boolean }[];
  /** Required with `accounts`: the record is never written with passwords in the clear. */
  password?: string;
}

const TEXT = {
  en: {
    title: 'Installation record',
    subtitle: (host: string) => `${host}, built by Velnox`,
    hostname: 'Hostname',
    vmid: 'VM ID',
    cluster: 'Cluster',
    node: 'Node',
    template: 'Template',
    os: 'Operating system',
    windows: 'Windows',
    linux: 'Linux',
    addresses: 'Addresses',
    none: 'none reported',
    requestedBy: 'Requested by',
    started: 'Started',
    finished: 'Finished',
    duration: 'Duration',
    minutes: (m: number) => `${m} min`,
    accounts: 'Accounts',
    account: 'Account',
    password: 'Password',
    admin: 'Administrator',
    yes: 'yes',
    no: 'no',
    keyOnly: 'key only',
    disabled: 'switched off',
    inVelnox:
      'The passwords are kept in Velnox. Open this installation there to reveal them; every reveal is recorded.',
    keep: 'This document holds passwords. Store it where you would store the passwords themselves.',
    footer: (v: string, d: string) => `Generated by Velnox ${v} on ${d}.`,
  },
  nl: {
    title: 'Installatieverslag',
    subtitle: (host: string) => `${host}, gebouwd door Velnox`,
    hostname: 'Hostnaam',
    vmid: 'VM-ID',
    cluster: 'Cluster',
    node: 'Node',
    template: 'Template',
    os: 'Besturingssysteem',
    windows: 'Windows',
    linux: 'Linux',
    addresses: 'Adressen',
    none: 'geen gemeld',
    requestedBy: 'Aangevraagd door',
    started: 'Gestart',
    finished: 'Klaar',
    duration: 'Duur',
    minutes: (m: number) => `${m} min`,
    accounts: 'Accounts',
    account: 'Account',
    password: 'Wachtwoord',
    admin: 'Beheerder',
    yes: 'ja',
    no: 'nee',
    keyOnly: 'alleen sleutel',
    disabled: 'uitgeschakeld',
    inVelnox:
      'De wachtwoorden worden in Velnox bewaard. Open deze installatie daar om ze te tonen; elke keer wordt vastgelegd.',
    keep: 'Dit document bevat wachtwoorden. Bewaar het zoals je de wachtwoorden zelf zou bewaren.',
    footer: (v: string, d: string) => `Gemaakt door Velnox ${v} op ${d}.`,
  },
} as const;

export function formatWhen(date: Date | null, locale: 'en' | 'nl', timeZone: string): string {
  if (!date) return '—';
  try {
    return new Intl.DateTimeFormat(locale === 'nl' ? 'nl-NL' : 'en-GB', {
      dateStyle: 'medium',
      timeStyle: 'short',
      timeZone,
    }).format(date);
  } catch {
    return date.toISOString();
  }
}

export async function renderRecord(input: RecordInput): Promise<Buffer> {
  if (input.accounts && !input.password) {
    throw new Error('A record with passwords is only ever written encrypted');
  }
  const t = TEXT[input.locale];
  // Nobody holds the owner password: the document is read, not edited.
  const ownerPassword = randomBytes(24).toString('base64url');
  const doc = new PDFDocument({
    size: 'A4',
    margin: 56,
    info: {
      Title: `${t.title} — ${input.hostname}`,
      Author: 'Velnox',
      Creator: `Velnox ${input.productVersion}`,
    },
    ...(input.password
      ? {
          pdfVersion: '1.7ext3' as const,
          userPassword: input.password,
          ownerPassword,
          permissions: { printing: 'highResolution' as const, copying: true },
        }
      : {}),
  });

  if (input.password) {
    // pdfkit writes revision 5; revision 6 is what ISO 32000-2 kept (pdf-r6.ts).
    upgradeEncryptionToR6(doc, { user: input.password, owner: ownerPassword });
  }

  const chunks: Buffer[] = [];
  doc.on('data', (chunk: Buffer) => chunks.push(chunk));
  const done = new Promise<void>((resolve, reject) => {
    doc.on('end', () => resolve());
    doc.on('error', reject);
  });

  doc.font('Helvetica-Bold').fontSize(20).text(t.title);
  doc
    .moveDown(0.2)
    .font('Helvetica')
    .fontSize(11)
    .fillColor('#555555')
    .text(t.subtitle(input.hostname));
  doc.fillColor('#000000').moveDown(1.2);

  const duration =
    input.startedAt && input.finishedAt
      ? t.minutes(
          Math.max(
            1,
            Math.round((input.finishedAt.getTime() - input.startedAt.getTime()) / 60_000),
          ),
        )
      : '—';
  const rows: [string, string][] = [
    [t.hostname, input.hostname],
    [t.vmid, input.vmid === null ? '—' : String(input.vmid)],
    [t.cluster, input.clusterName],
    [t.node, input.node],
    [t.template, input.templateName],
    [t.os, input.family === 'WINDOWS' ? t.windows : t.linux],
    [t.addresses, input.addresses.length ? input.addresses.join(', ') : t.none],
    [t.requestedBy, input.requestedBy ?? '—'],
    [t.started, formatWhen(input.startedAt, input.locale, input.timeZone)],
    [t.finished, formatWhen(input.finishedAt, input.locale, input.timeZone)],
    [t.duration, duration],
  ];
  for (const [label, value] of rows) {
    const y = doc.y;
    doc.font('Helvetica-Bold').fontSize(10).text(label, 56, y, { width: 150 });
    doc.font('Helvetica').fontSize(10).text(value, 210, y, { width: 330 });
    doc.moveDown(0.4);
  }

  doc.moveDown(1).font('Helvetica-Bold').fontSize(13).text(t.accounts, 56);
  doc.moveDown(0.4);
  if (input.accounts) {
    const header = doc.y;
    doc.font('Helvetica-Bold').fontSize(10);
    doc.text(t.account, 56, header, { width: 150 });
    doc.text(t.password, 210, header, { width: 220 });
    doc.text(t.admin, 440, header, { width: 100 });
    doc.moveDown(0.4);
    for (const account of input.accounts) {
      const y = doc.y;
      doc.font('Helvetica').fontSize(10).text(account.name, 56, y, { width: 150 });
      doc
        .font(account.password ? 'Courier' : 'Helvetica-Oblique')
        .text(
          account.password ?? (account.name === 'Administrator' ? t.disabled : t.keyOnly),
          210,
          y,
          {
            width: 220,
          },
        );
      doc.font('Helvetica').text(account.administrator ? t.yes : t.no, 440, y, { width: 100 });
      doc.moveDown(0.4);
    }
    doc.moveDown(0.8).font('Helvetica-Oblique').fontSize(9).text(t.keep, 56);
  } else {
    doc.font('Helvetica').fontSize(10).text(t.inVelnox, 56);
  }

  doc
    .moveDown(2)
    .font('Helvetica')
    .fontSize(8)
    .fillColor('#777777')
    .text(t.footer(input.productVersion, formatWhen(new Date(), input.locale, input.timeZone)), 56);
  doc.end();
  await done;
  return Buffer.concat(chunks);
}
